---
- name: ansible conditional statement
  hosts: localhost
  gather_facts: false
  vars: 
    a: 30
    b: 6
  tasks:
    - name: setting larger fact using set_facts
      set_fact: 
        larger: "{{a if a>b else b}}"
    - name: finding largervalue with condition
      debug:
        msg:
          - "the larger value is : {{larger}}"
    

