---
- name: Installing webserver on target nodes based on their Linux Distro
  hosts: controller, centos
  become: true
  gather_facts: true
  tasks:
    - name: Installing httpd on RedHat
      yum:
        name: httpd
        state: absent
        update_cache: true
      when: ansible_os_family == "RedHat"

    - name: Installing apache2 on Debian
      apt:
        name: apache2
        state: absent
        update_cache: true
      when: ansible_os_family == "Debian"

    - name: Starting Webservers
      service:
        name: "{{ if ansible_os_family == RedHat httpd else apache2 }}"
        state: started