---
- name: Installing packages on RHEL 
  yum:
    name: "{{PkgName.get(ansible_facts.os_family)}}"
    state: present
    update_cache: true
  when: ansible_facts.os_family == "RedHat"

- name: Installing packages on Ubuntu 
  apt:
    name: "{{PkgName.get(ansible_facts.os_family)}}"
    state: present
    update_cache: true
  when: ansible_facts.os_family == "Ubuntu"

- name: copying the the index.html file in /var/www/html
  template:
    src: index.j2
    dest: /var/www/html/index.html
  notify: Restart the Webserver
