---
- name: testing the template module
  hosts: ubuntu, centos
  gather_facts: true
  vars:
    pkgName:
      RedHat: httpd
      Debian: apache2
  become: yes
  tasks:
    - name: Removing packages on RHEL]
      yum:
        name: "{{pkgName.get(ansible_facts.os_family)}}"
        state: absent
        update_cache: true
      when: ansible_facts.os_family == "RedHat"

    - name: Removing packages on Debian
      apt:
        name: "{{pkgName.get(ansible_facts.os_family)}}"
        state: absent
        update_cache: true
      when: ansible_facts.os_family == "Debian"
