---
- name: using handlers
  hosts: localhost
  become: yes
  gather_facts: true
  tasks:
    - name: installing nginx msg
      debug:
        msg: "Installing nginx"

    - name: checking the version
      command:
        cmd: 'nginx -v'
      register: nginxVersion

    - name: Installing nginx
      apt:
        name: nginx
        state: present
      failed_when: nginxVersion.rc == 0