---
- name: ansible membership operator
  hosts: localhost
  gather_facts: false
  vars:
    x: 40
    my_name: "ansible"
    my_path: /home/ironman/test/mytest
  tasks:
    - name: printing 
      debug:
        msg:
          - "x is define: {{x is defined}}"
          - "y is defined {{y is defined}}"
          - "z is defined {{z is defined}}"
          - "my_name is lower: {{my_name is lower}}"
          - "my_name is upper: {{my_name is upper}}"
          - "my_name is string: {{my_name is string}}"
          - "x is devisible by 2: {{x is divisibleby 2}}"
          - "x is even {{x is even}}"
          - "x is odd {{x is odd}}"
          # - "hello is lower {{hello is lower }}"